#!/bin/bash
# Helper script for commands related to this repository.
#
# Notes:
#  - Changes to template only require user to refresh browser.
#  - Changes to static files require the 'static' command to be run.
#  - Changes to Python code are detected by gunicorn and should take effect
#    on the server after a few seconds.

set -e

ERROR='\033[0;31m'
SUCCESS='\033[0;32m'
CODE='\033[0;36m'
NC='\033[0m' # No Color

cmd_helps=()

defhelp() {
  local command="${1?}"
  local text="${2?}"
  local help_str
  help_str="$(printf '   %-28s %s' "$command" "$text")"
  cmd_helps+=("$help_str")
}

# Print out help information
cmd_help() {
  echo "Script for performing tasks related to the codeWOF repository."
  echo
  echo "Usage: ./dev [COMMAND]"
  echo "Replace [COMMAND] with a word from the list below."
  echo
  echo "COMMAND list:"
  for str in "${cmd_helps[@]}"; do
    echo -e "$str"
  done
}
defhelp help 'View all help.'

# Start development environment
cmd_start() {
  echo "Creating systems..."
  docker-compose -f docker-compose.local.yml up -d
  # Alert user that system is ready
  echo -e "\n${SUCCESS}System is up!${NC}"
  echo -e "Run the command ${CODE}./dev update${NC} to load content."
}
defhelp start 'Start development environment.'

# Stop development environment
cmd_end() {
  echo "Stopping systems..."
  docker-compose -f docker-compose.local.yml down
}
defhelp end 'Stop development environment.'

cmd_restart() {
  docker-compose -f docker-compose.local.yml restart "$@"
}
defhelp restart 'Restart container.'

# Update all content
cmd_update() {
  cmd_static

  echo ""
  cmd_migrate

  echo ""
  cmd_update_data

  echo ""
  cmd_collect_static

  echo -e "\n${SUCCESS}Content is loaded!${NC}"
  echo "Open your preferred web browser to the URL 'codewof.localhost'"
}
defhelp update 'Update system ready for use.'

# Run Django makemigrations command
# Run in exising container to use existing volumes
cmd_makemigrations() {
  echo "Creating database migrations..."
  docker-compose -f docker-compose.local.yml exec django python ./manage.py makemigrations --no-input
}
defhelp makemigrations 'Run Django makemigrations command.'

# Run Django migrate command
# Run in exising container to access new migration files
cmd_migrate() {
  echo "Applying database migrations..."
  docker-compose -f docker-compose.local.yml exec django python ./manage.py migrate
}
defhelp migrate 'Run Django migrate command.'

### Data related commands #################################

# Run update_data command
cmd_update_data() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py update_data
}
defhelp update_data "Update all required data."

# Run load_user_types command
cmd_load_user_types() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py load_user_types
}
defhelp load_user_types "Load user types."

# Run load_questions command
cmd_load_questions() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py load_questions
}
defhelp load_questions "Load questions."

# Run load_style_errors command
cmd_load_style_errors() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py load_style_errors
}
defhelp load_style_errors "Load style errors."

# Run load_achievements command
cmd_load_achievements() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py load_achievements
}
defhelp load_achievements "Load achievements."

cmd_createsuperuser() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py createsuperuser
}
defhelp createsuperuser "Create superuser in Django system."

cmd_sample_data() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py sample_data $1
}
defhelp sample_data "Add sample data to website."

cmd_send_email_reminders() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py send_email_reminders
}
defhelp send_email_reminders "Send an email reminder to all users who opted to receive one today."

cmd_raise_backdate_flags() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py raise_backdate_flags
}
defhelp raise_backdate_flags 'Raise a flag on all user profiles, requiring a backdate be done on them.'

cmd_remove_expired_invitations() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py remove_expired_invitations
}
defhelp remove_expired_invitations "Remove all Invitation objects where date_expires is before the current datetime."

cmd_backdate() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py backdate_points_and_achievements --ignore_flags
}
defhelp backdate 'Re-calculate points and achievements earned for all user profiles.'

###########################################################

# Build static files
cmd_static() {
  echo "Building static files..."
  docker-compose -f docker-compose.local.yml run --rm node npm run dev
}
defhelp static 'Build static files.'

# Collecting static files
cmd_collect_static() {
  echo
  echo "Collecting static files..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python manage.py collectstatic --no-input --clear
}
defhelp collect_static "Collecting static files."

# Update and collect static files
cmd_update_static() {
  cmd_static
  echo ""
  cmd_collect_static
  echo ""
  echo -e "\n${SUCCESS}Static files are updated!${NC}"
}
defhelp update_static 'Update static files.'

# Build Docker images
cmd_build() {
  echo "Building Docker images..."
  docker-compose -f docker-compose.local.yml build
}
defhelp build 'Build or rebuild Docker images.'

# Run exec
cmd_exec() {
  docker-compose -f docker-compose.local.yml exec "$@"
}
defhelp exec "Execute command in given container."

# View Docker logs
cmd_logs() {
  echo "Building Docker images..."
  docker-compose -f docker-compose.local.yml logs --timestamps "$@"
}
defhelp logs 'View logs.'

# Run style checks
cmd_style() {
  echo "Running PEP8 style checker..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django flake8
  pep8_status=$?
  echo
  echo "Running Python docstring checker..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django pydocstyle --count --explain
  pydocstyle_status=$?
  ! (( pep8_status || pydocstyle_status ))
}
defhelp style 'Run style checks.'

# Run test suite
cmd_test_suite() {
  echo "Running test suite..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django coverage run --rcfile=./.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --nomigrations
}
defhelp test_suite 'Run test suite with code coverage.'

# Run specific test suite
cmd_test_specific() {
  echo "Running specific test suite..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py test --settings=config.settings.testing "${1}" -v 3 --nomigrations
}
defhelp test_specific 'Run specific test suite. Pass in parameter of Python test module.'

# Display test coverage table
cmd_test_coverage() {
  echo "Displaying test suite coverage..."
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django coverage xml -i
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django coverage report -m --skip-covered
}
defhelp test_coverage 'Display code coverage report.'

cmd_createsuperuser() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django python ./manage.py createsuperuser
}
defhelp createsuperuser "Create superuser in Django system."

# --- Testing -----------------------------------------------------------------
# For use in GitHub Actions environment

cmd_ci() {
  docker network create uccser-development-proxy
  cmd_start
  local cmd="$1"
  shift
  if [ -z "$cmd" ]; then
    echo -e "${ERROR}ERROR: ci command requires one parameter!${NC}"
    cmd_help
    exit 1
  fi
  if silent type "cmd_$cmd"; then
    "cmd_$cmd" "$@"
    exit $?
  else
    echo -e "${ERROR}ERROR: Unknown command!${NC}"
    echo "Type './dev help' for available commands."
    exit 1
  fi
}

cmd_test_general() {
  docker-compose -f docker-compose.local.yml run --rm --label traefik.enable=false django coverage run --rcfile=./.coveragerc ./manage.py test --settings=config.settings.testing --pattern "test_*.py" -v 3 --exclude-tag=resource --exclude-tag=management --nomigrations
}

# --- Core script logic -------------------------------------------------------

silent() {
  "$@" > /dev/null 2>&1
}

# If no command given
if [ $# -eq 0 ]; then
  echo -e "${ERROR}ERROR: This script requires a command!${NC}"
  cmd_help
  exit 1
fi
cmd="$1"
shift
if silent type "cmd_$cmd"; then
  "cmd_$cmd" "$@"
  exit $?
else
  echo -e "${ERROR}ERROR: Unknown command!${NC}"
  echo "Type './dev help' for available commands."
  exit 1
fi
