# This Dockerfile is based off the Google App Engine Python runtime image
# https://github.com/GoogleCloudPlatform/python-runtime
FROM uccser/django:2.1.5-with-weasyprint

# Add metadata to Docker image
LABEL maintainer="csse-education-research@canterbury.ac.nz"

# Set terminal to be noninteractive
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
        binutils \
        libproj-dev \
        gdal-bin \
      --no-install-recommends --no-install-suggests \
    && apt-get -y --purge autoremove \
    && rm -rf /var/lib/apt/lists/*

ENV DJANGO_PRODUCTION=False
EXPOSE 8080

# Copy and create virtual environment
COPY requirements /requirements

# Install dependencies
RUN /docker_venv/bin/pip3 install -r /requirements/local.txt

RUN mkdir /codewof/
RUN mkdir /codewof/codewof/
WORKDIR /codewof/codewof/

# Copy and install fonts
COPY codewof/static/fonts/ /usr/share/fonts/
RUN fc-cache -fv
