runtime: custom
env: flex

beta_settings:
    cloud_sql_instances: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}

env_variables:
  DEPLOYMENT: ${DEPLOYMENT}
  INCLUDE_INCONTEXT_L10N: ${INCLUDE_INCONTEXT_L10N}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  GOOGLE_CLOUD_SQL_DATABASE_USERNAME: ${GOOGLE_CLOUD_SQL_DATABASE_USERNAME}
  GOOGLE_CLOUD_SQL_DATABASE_PASSWORD: ${GOOGLE_CLOUD_SQL_DATABASE_PASSWORD}
  GOOGLE_CLOUD_SQL_CONNECTION_NAME: ${GOOGLE_CLOUD_SQL_CONNECTION_NAME}
  GOOGLE_CLOUD_STORAGE_BUCKET_STATIC_NAME: ${GOOGLE_CLOUD_STORAGE_BUCKET_STATIC_NAME}
  GOOGLE_CLOUD_STORAGE_BUCKET_MEDIA_NAME: ${GOOGLE_CLOUD_STORAGE_BUCKET_MEDIA_NAME}
  GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
  MAILGUN_API_KEY: ${MAILGUN_API_KEY}
  RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
  RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}

resources:
  cpu: 1
  memory_gb: 3.75

liveness_check:
  path: "/gae/liveness_check"

readiness_check:
  path: "/gae/readiness_check"
