# Generated by Django 2.1.5 on 2019-08-05 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='users',
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='codewof.Question'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='research.Study'),
        ),
        migrations.AlterField(
            model_name='studyregistration',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='research.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='studyregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
