# Generated by Django 2.1.5 on 2019-08-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['start_date', 'end_date'], 'verbose_name': 'study', 'verbose_name_plural': 'studies'},
        ),
    ]
