# Generated by Django 2.1.5 on 2019-08-13 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('users', '0001_initial'),
        ('programming', '0002_auto_20190813_1548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='programming.Question'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='research.Study'),
        ),
        migrations.AddField(
            model_name='study',
            name='user_types',
            field=models.ManyToManyField(blank=True, help_text='Which types of users is this research study visible and open to.', related_name='studies', to='users.UserType', verbose_name='Open to user types'),
        ),
    ]
