# Generated by Django 2.1.5 on 2019-08-28 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_auto_20190813_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='studies_researching', to=settings.AUTH_USER_MODEL),
        ),
    ]
