# Generated by Django 2.1.5 on 2019-08-04 23:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20190805_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='title'),
        ),
    ]
