# Generated by Django 2.1.5 on 2019-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190812_0150'),
        ('research', '0002_auto_20190805_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='user_types',
            field=models.ManyToManyField(blank=True, help_text='Which types of users is this research study visible and open to.', related_name='studies', to='users.UserType', verbose_name='Open to user types'),
        ),
    ]
