# Generated by Django 2.1.5 on 2019-08-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190805_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='consent_form',
            field=models.CharField(blank=True, help_text='Name of class for consent form.', max_length=200),
        ),
    ]
