# Generated by Django 2.0.4 on 2018-04-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.CharField(max_length=100)),
                ('expected_output', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='skill_areas',
            field=models.ManyToManyField(to='questions.SkillArea'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_cases',
            field=models.ManyToManyField(to='questions.TestCase'),
        ),
    ]
