# Generated by Django 2.0.4 on 2018-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180418_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere_token', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='skill_areas',
            field=models.ManyToManyField(related_name='questions', to='questions.SkillArea'),
        ),
    ]
