# Generated by Django 2.0.4 on 2018-05-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180422_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
