# Generated by Django 2.0.4 on 2018-05-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='function_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testcase',
            name='function_params',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_input',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
