# Generated by Django 2.0.4 on 2018-05-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180502_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='expected_return',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
