# Generated by Django 2.0.4 on 2018-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_return',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
