# Generated by Django 2.0.4 on 2018-07-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20180723_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(blank=True, to='questions.Skill'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='skills_hinted',
            field=models.ManyToManyField(blank=True, to='questions.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='subskills',
            field=models.ManyToManyField(blank=True, to='questions.Skill'),
        ),
    ]
