# Generated by Django 2.0.4 on 2018-07-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20180723_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='passed_tests',
            field=models.BooleanField(default=False),
        ),
    ]
