# Generated by Django 2.0.4 on 2018-07-25 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20180725_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='attempts',
            new_name='attempted_questions',
        ),
    ]
