# Generated by Django 2.0.4 on 2018-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_question_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, default='The question maker has not specified an ideal solution to this question'),
        ),
    ]
