# Generated by Django 2.0.4 on 2018-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20180803_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(default='The question maker has not specified a solution to this question'),
        ),
    ]
