# Generated by Django 2.0.4 on 2018-09-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20180806_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Profile')),
            ],
        ),
    ]
