# Generated by Django 2.0.4 on 2018-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_loginday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earned',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
