# Generated by Django 2.0.4 on 2018-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20180902_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='buggy_program',
            field=models.TextField(blank=True),
        ),
    ]
