# Generated by Django 2.0.4 on 2018-09-21 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_question_buggy_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
