# Generated by Django 2.0.4 on 2018-09-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20180922_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='buggy_program',
        ),
        migrations.RemoveField(
            model_name='question',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='function_params',
        ),
        migrations.CreateModel(
            name='Buggy',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
                ('buggy_program', models.TextField(blank=True)),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question')),
            ],
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TestCaseFunction',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.TestCase')),
                ('function_params', models.CharField(blank=True, max_length=500)),
                ('expected_return', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('questions.testcase',),
        ),
        migrations.CreateModel(
            name='TestCaseProgram',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.TestCase')),
            ],
            bases=('questions.testcase',),
        ),
        migrations.CreateModel(
            name='BuggyFunction',
            fields=[
                ('buggy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Buggy')),
                ('function_name', models.CharField(blank=True, max_length=100)),
            ],
            bases=('questions.buggy',),
        ),
        migrations.CreateModel(
            name='ProgrammingFunction',
            fields=[
                ('programming_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Programming')),
                ('function_name', models.CharField(blank=True, max_length=100)),
            ],
            bases=('questions.programming',),
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.AddField(
            model_name='testcaseprogram',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Programming'),
        ),
        migrations.AddField(
            model_name='testcasefunction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.ProgrammingFunction'),
        ),
    ]
