# Generated by Django 2.0.4 on 2018-09-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0030_auto_20180923_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buggy',
            options={'verbose_name': 'Program Debugging Question'},
        ),
        migrations.AlterModelOptions(
            name='buggyfunction',
            options={'verbose_name': 'Function Debugging Question'},
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': 'Program Programming Question'},
        ),
        migrations.AlterModelOptions(
            name='programmingfunction',
            options={'verbose_name': 'Function Programming Question'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Parsons Problem'},
        ),
        migrations.AlterModelOptions(
            name='testcasefunction',
            options={'verbose_name': 'Function Test Case'},
        ),
        migrations.AlterModelOptions(
            name='testcaseprogram',
            options={'verbose_name': 'Program Test Case'},
        ),
    ]
