# Generated by Django 2.0.4 on 2018-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20180923_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buggy',
            name='buggy_program',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='buggyfunction',
            name='function_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programmingfunction',
            name='function_name',
            field=models.CharField(max_length=100),
        ),
    ]
