# Generated by Django 2.2.3 on 2021-06-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210626_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='person',
            new_name='user',
        ),
    ]
