# Generated by Django 3.2.6 on 2021-09-02 04:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210822_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_expires',
            field=models.DateTimeField(default=users.models.get_default_invitation_expiry),
        ),
    ]
