# Generated by Django 2.2.3 on 2021-06-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210629_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
