# Generated by Django 2.1.5 on 2020-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('original_message', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('title_templated', models.TextField(blank=True)),
                ('solution', models.TextField()),
                ('explanation', models.TextField()),
            ],
        ),
    ]
