# Generated by Django 2.1.5 on 2020-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
