# Generated by Django 3.2.16 on 2022-12-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_alter_error_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='error',
            constraint=models.UniqueConstraint(fields=('language', 'code'), name='unique_language_code'),
        ),
    ]
