# Generated by Django 2.1.5 on 2019-08-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codewof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeDebugging',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='codewof.Question')),
                ('read_only_lines_top', models.PositiveSmallIntegerField(default=0)),
                ('read_only_lines_bottom', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Debugging Problem Question',
            },
            bases=('codewof.question',),
        ),
        migrations.CreateModel(
            name='QuestionTypeDebuggingTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='codewof.TestCase')),
                ('test_code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='codewof.QuestionTypeDebugging')),
            ],
            options={
                'verbose_name': 'Debugging Problem Question Test Case',
            },
            bases=('codewof.testcase',),
        ),
    ]
