# Generated by Django 2.1.5 on 2019-08-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewof', '0002_questiontypedebugging_questiontypedebuggingtestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontypedebugging',
            name='initial_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
