# Generated by Django 2.1.5 on 2019-07-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codewof', '0003_profile_earned_badges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginDay',
            new_name='DayWithAttempt',
        ),
    ]
