# Generated by Django 2.1.5 on 2019-07-31 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codewof', '0004_auto_20190724_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daywithattempt',
            name='profile',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='earned',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DayWithAttempt',
        ),
    ]
