# Generated by Django 2.1.5 on 2019-07-31 22:30

import codewof.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewof', '0005_auto_20190801_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='datetime',
            field=models.DateTimeField(default=codewof.models.get_local_time),
        ),
        migrations.AlterField(
            model_name='earned',
            name='date',
            field=models.DateTimeField(default=codewof.models.get_local_time),
        ),
    ]
