# Generated by Django 2.1.5 on 2019-09-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_auto_20190904_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_tier',
            field=models.IntegerField(default=0),
        ),
    ]
