# Generated by Django 2.1.5 on 2019-10-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_badge_badge_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.Badge'),
        ),
    ]
