# Generated by Django 2.1.5 on 2020-04-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_badge_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempted_questions',
            field=models.ManyToManyField(through='programming.Attempt', to='programming.Question'),
        ),
    ]
