# Generated by Django 2.1.5 on 2020-04-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0006_profile_attempted_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earned',
            options={'verbose_name': 'Earned badge', 'verbose_name_plural': 'Badges earned'},
        ),
    ]
