# Generated by Django 2.1.5 on 2020-04-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0007_auto_20200409_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
