# Generated by Django 2.2.3 on 2020-04-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0008_auto_20200415_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['badge_tier']},
        ),
    ]
