# Generated by Django 2.2.3 on 2020-04-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0009_auto_20200417_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_backdated',
            field=models.BooleanField(default=False),
        ),
    ]
