# Generated by Django 2.2.3 on 2020-05-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0010_profile_has_backdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='has_backdated',
            field=models.BooleanField(default=False),
        ),
    ]
