# Generated by Django 2.2.3 on 2020-06-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0011_auto_20200519_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badge',
            new_name='Achievement',
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['achievement_tier']},
        ),
        migrations.AlterModelOptions(
            name='earned',
            options={'verbose_name': 'Earned achievement', 'verbose_name_plural': 'Achievements earned'},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='badge_tier',
            new_name='achievement_tier',
        ),
        migrations.RenameField(
            model_name='earned',
            old_name='badge',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='earned_badges',
            new_name='earned_achievements',
        ),
    ]
