# Generated by Django 3.2.6 on 2021-09-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0013_auto_20210902_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.TextField()),
                ('hint', models.TextField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='QuestionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=500)),
                ('css_class', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField()),
                ('hint', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='programming.questioncontext')),
            ],
            options={
                'ordering': ['number', 'context'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammingConcepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=500)),
                ('css_class', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField()),
                ('hint', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='programming.programmingconcepts')),
            ],
            options={
                'ordering': ['number', 'concept'],
            },
        ),
    ]
