# Generated by Django 3.2.11 on 2022-04-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0013_auto_20210902_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('level', models.PositiveSmallIntegerField()),
                ('name', models.TextField()),
                ('hint', models.TextField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
