# Generated by Django 3.2.6 on 2021-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0015_question_difficulty_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmingconcepts',
            options={'ordering': ['number', 'name']},
        ),
        migrations.RenameField(
            model_name='programmingconcepts',
            old_name='concept',
            new_name='name',
        ),
        migrations.AddField(
            model_name='programmingconcepts',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='concepts',
            field=models.ManyToManyField(blank=True, null=True, related_name='concepts', to='programming.ProgrammingConcepts'),
        ),
    ]
