# Generated by Django 3.2.6 on 2021-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0016_auto_20210915_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='concepts',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='programming.ProgrammingConcepts'),
        ),
    ]
