# Generated by Django 3.2.6 on 2021-09-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0017_alter_question_concepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='concepts',
            field=models.ManyToManyField(related_name='concepts', to='programming.ProgrammingConcepts'),
        ),
    ]
