# Generated by Django 3.2.6 on 2021-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0018_alter_question_concepts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionContext',
            new_name='QuestionContexts',
        ),
        migrations.AddField(
            model_name='question',
            name='contexts',
            field=models.ManyToManyField(related_name='contexts', to='programming.QuestionContexts'),
        ),
    ]
