# Generated by Django 3.2.11 on 2022-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0019_alter_question_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingconcepts',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
