# Generated by Django 3.2.6 on 2021-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0019_auto_20210920_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontexts',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
