# Generated by Django 3.2.6 on 2021-09-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0020_questioncontexts_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncontexts',
            options={'ordering': ['number', 'name']},
        ),
        migrations.RenameField(
            model_name='questioncontexts',
            old_name='context',
            new_name='name',
        ),
    ]
