# Generated by Django 3.2.11 on 2022-09-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0020_programmingconcepts_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontexts',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
    ]
