# Generated by Django 3.2.16 on 2022-12-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0021_questioncontexts_has_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='type',
            field=models.CharField(default='Program', max_length=100),
        ),
    ]
