# Generated by Django 3.2.6 on 2021-10-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0021_auto_20210920_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontexts',
            name='indentation_level',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
