# Generated by Django 3.2.18 on 2023-10-01 16:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0022_testcase_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('question_type', models.CharField(default='Program', max_length=100)),
                ('question_text', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_drafts', to='programming.profile')),
                ('concepts', models.ManyToManyField(related_name='draft_concepts', to='programming.ProgrammingConcepts')),
                ('contexts', models.ManyToManyField(related_name='draft_contexts', to='programming.QuestionContexts')),
                ('difficulty_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='programming.difficultylevel')),
            ],
            options={
                'verbose_name': 'Draft',
                'verbose_name_plural': 'Drafts',
            },
        ),
    ]
