# Generated by Django 3.2.18 on 2023-10-15 16:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0023_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='initial_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='lines',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='read_only_lines_bottom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draft',
            name='read_only_lines_top',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DraftTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(default='Program', max_length=100)),
                ('expected_output', models.TextField(blank=True)),
                ('test_code', models.TextField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_test_cases', to='programming.draft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
