# Generated by Django 3.2.18 on 2023-10-19 19:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0024_auto_20231016_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to='programming.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to='programming.question')),
            ],
        ),
        migrations.CreateModel(
            name='MacroValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('value', models.TextField()),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_values', to='programming.macro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftMacroValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('value', models.TextField()),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_values', to='programming.draftmacro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
