# Generated by Django 3.2.6 on 2021-10-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0025_rename_indent_level_questioncontexts_indentation_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncontexts',
            name='indentation_level',
        ),
    ]
