# Generated by Django 3.2.6 on 2021-10-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0026_remove_questioncontexts_indentation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontexts',
            name='indent_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
