# Generated by Django 3.2.6 on 2021-10-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0027_questioncontexts_indent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingconcepts',
            name='indent_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
