# Generated by Django 3.2.6 on 2021-10-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0029_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='Program', max_length=100),
        ),
    ]
